### ISSUE TITLE
react-admin-rte always triggers DirtyHandler promptmessage when cancelling

### ISSUE THREAD

**Issue by raphaelblum** [vivid-planet/comet-admin#201]
when a rte-field is in a final-form, the promptmessage "Nicht gespeicherte Änderungen verwerfen?" always shows when pressing cancel even if there are no changes.

**Comment by rabengraph** [comment]
@raphaelblum Und du meinst dass die Ursache dafür die ist, dass der field-value beim rte-field com type `object` ist und nicht `string` oder ?

**Comment by raphaelblum** [comment]
ich bin mir noch nicht sicher woran das genau liegt, ich würd mir das sonst bald mal anschauen und fixen versuchen.
