### ISSUE TITLE
changelog for next

### ISSUE THREAD

**Issue by fraxachun** [vivid-planet/comet-admin#240]
If something is missing, quote changes here, I will formulate them into CHANGELOG.md

Breaking:
- Consolidated packages to @vivid-planet/react-admin
- New versioning scheme
- react-intl
- Update apollo & graphql

Highlights:
- Hooks for EditDialog, ...

**Comment by rabengraph** [comment]
Breaking:

- Probably 'removal of date-fns', if this is gonna happen in the first 0.1 release

**Comment by nsams** [comment]
EditDialog (...) Hooks are already released (current alpha)

**Comment by fraxachun** [comment]
The following packages have been consolidated into `@vivid-planet/react-admin`

- @vivid-planet/react-admin-core
- @vivid-planet/fetch-provider
- @vivid-planet/material-ui-react-select
- @vivid-planet/react-admin-color-picker
- @vivid-planet/react-admin-date-fns
- @vivid-planet/react-admin-final-form-material-ui
- @vivid-planet/react-admin-form
- @vivid-planet/react-admin-layout
- @vivid-planet/react-admin-mui

The following imports have been prefixed with `FinalForm`
- Checkbox
- Input
- Radio
- ReactSelect, ReactSelectAsync, ReactSelectCreatable, ReactSelectAsyncCreateable
- ReactSelectStaticOptions
- TextField
- ColorPicker
- DatePicker, DateRangePicker
- createRteField (=> createFinalFormRte)
