### ISSUE TITLE
Replace react-select with material-ui autocomplete?

### ISSUE THREAD

**Issue by fraxachun** [vivid-planet/comet-admin#242]
https://material-ui.com/components/autocomplete/

> It's meant to be an improved version of the "react-select" and "downshift" packages.

Only a suggestion, I didn't yet really go into the details...

**Comment by rabengraph** [comment]
I took a brief look,
looks really good!

**Comment by nsams** [comment]
Autocomplete sounds too heavy (just from the name!) 

Big thing is how it manages displayed value on load. static-select allows to use a custom (complex) value type and generate the displayed value from it.

Autocomplete seems to have a second value (inputValue): https://material-ui.com/components/autocomplete/#controllable-states for solving this issue. This needs to be tested how it can be integrated into a form.

**Comment by fraxachun** [comment]
I've created a first implementation: https://github.com/vivid-planet/react-admin/pull/250

**Comment by fraxachun** [comment]
https://github.com/vivid-planet/comet-admin/pull/250
