### ISSUE TITLE
StackApi: Make payload optional?

### ISSUE THREAD

**Issue by johnnyomair** [vivid-planet/comet-admin#290]
For some cases (e.g. an "Add" page), it might be helpful to make the payload (which is basically the entity's ID) optional instead of creating Routes like `/pages/add/new`. What do you think?

**Comment by nsams** [comment]
How common is a page used excursively for adding?

I often used a single page for editing and adding (as the form looks basically 100% the same)

**Comment by johnnyomair** [comment]
I've thought about other examples and couldn't think of any.
